run_env: prod
root_dir: prod_data
date_range:
  start: 2025-01-01
  end: today

datasets:
  - source: tushare
    name: stock_list
    enabled: true

  - source: tushare
    name: stock_st
    enabled: true

  - source: tushare
    name: stock_daily
    enabled: true

  - source: tushare
    name: etf_list
    enabled: true

  - source: tushare
    name: market_bars_etf_daily
    enabled: true

  - source: tushare
    name: index_list
    enabled: true
    params:
      markets:
        - SSE
        - SZSE
        - CSI

  - source: tushare
    name: market_bars_index_daily
    enabled: true
    params:
      index_codes:
        - 000001.SH
        - 000016.SH
        - 000010.SH
        - 000300.SH
        - 000903.SH
        - 000510.SH
        - 000905.SH
        - 000906.SH
        - 000852.SH
        - 399001.SZ
        - 399330.SZ
        - 399006.SZ
        - 399673.SZ
        - 399303.SZ
        - 000688.SH
        - 000698.SH
        - 000699.SH
        - 399975.SZ
        - 399986.SZ
        - 399989.SZ
        - 399967.SZ
        - 399808.SZ
        - 399976.SZ
        - 000061.SH
        - 000140.CSI
        - 930916.CSI
        - 931018.CSI
        - 931552.CSI
        - 932200.CSI
        - 950175.CSI
        - 950243.CSI
        - 950245.CSI
        - H01077.CSI
        - H11077.CSI
        - H20914.CSI
        - 980080.CNI

  - source: tushare
    name: market_bars_index_daily
    enabled: true
    params:
      api: index_global
      index_codes:
        - HKTECH

  - source: tushare
    name: market_bars_index_daily
    enabled: true
    params:
      api: fut_index_daily
      index_codes:
        - M.NH
        - NHFI.NH
        - NHECI.NH
        - T.NH
        - TL.NH
        - AU.NH

  - source: tushare
    name: future_list
    enabled: true
    params:
      exchanges:
        - CFFEX
        - DCE
        - CZCE
        - SHFE
        - INE
        - GFEX

  - source: tushare
    name: market_bars_future_daily
    enabled: true

  - source: tushare
    name: market_fx_daily
    enabled: true
    params:
      ts_codes:
        - USDCNH.FXCM
        - USDHKD.FXCM

  - source: yfinance
    name: yf_instrument
    enabled: true
    params:
      tickers:
        - 3032.HK
        - ONEQ
        - ^NDX
        - GOOG
        - NVDA
        - CVX

  - source: yfinance
    name: yf_market_bars_daily
    enabled: true
    params:
      interval: 1d
      auto_adjust: false
      actions: true # 载行情时同时带上分红和拆股信息
      repair: false
      threads: true # 多 ticker 下载时启用并发线程
